### ISSUE TITLE
Trying to create a new wallet doesn't work

### ISSUE THREAD

**Issue by ynx0** [uqbar-dao/wallet-ui#10]
Title. I keep getting thrown directly to `"Mnemonic is required"`. I think it's because if you cancel out of creating the wallet, the mnemonic is null. But the UI never gives you a chance to input a mnemonic a second time.

Refreshing does not seem to fix.

**Comment by marcoleder** [comment]
https://github.com/uqbar-dao/wallet-ui/blob/e38fbfa3b67b3c43d874bd031ee9fc868e76a1a5/src/views/AccountsView.tsx#L54

and

https://github.com/uqbar-dao/wallet-ui/blob/e38fbfa3b67b3c43d874bd031ee9fc868e76a1a5/src/views/AccountsView.tsx#L160
