### ISSUE TITLE
Various UX issues in the Account tab

### ISSUE THREAD

**Issue by ynx0** [uqbar-dao/wallet-ui#14]
## Problem 1 - Account specific page
When I click into an account, I get taken from `http://localhost:3000/apps/uqbar-wallet/accounts` to `http://localhost:3000/apps/uqbar-wallet/accounts/0x7772b8a76840892229035b287494436f8850713c` but there is basically no visual indication that I have entered a separate view, and the account's tab is still highlighted. It looks like I'm on the same page but everything disappeared, and refreshing doesn't get me back (rightly so). 

There should be more visual indication that the view has changed (breadcrumbs or smtn), and also a back button.

## Problem 2 - Account nonces
Also, when there are no nonces to be displayed there should be some sort of positive message that states so, i.e. `No nonces to display. Make a transaction and you should see one here!` or something like that.

Otherwise there's no way to tell if it just bugged out and wasn't able to load.

## Problem 3 - nick field
There should be some toast/visual feedback that editing the nick of a pubkey succeeded. Right now it just feels like I'm editing a frontend that hasn't been hooked up to anything, even though the changes do actually make it to the backend

Also, I didn't even know they were editable until I accidently highlighted them. They should either present themselves as such (with styling etc.) or there should be some dedicated edit view or something.

**Comment by willbach** [comment]
These have been addressed or are no longer relevant after changes made in the last 3 months.
